### ISSUE TITLE
start meeting not working

### ISSUE THREAD

**Issue by Adil-Ashfaq35** [ManpraXSoftware/zoom_allinonesdk#2]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ZoomError: Error starting meeting: Exception: Failed to fetch data: Exception: Failed to log in: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
E/flutter (29582): The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
E/flutter (29582): Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
E/flutter (29582): In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
E/flutter (29582): 
E/flutter (29582): #0      MethodChannelZoomAllInOneSdk.startMeeting (package:zoom_allinonesdk/zoom_allinonesdk_method_channel.dart:134:7)
E/flutter (29582): <asynchronous suspension>
E/flutter (29582): #1      _MeetingWidgetState.startMeetingAndroidAndIOS.<anonymous closure>.<anonymous closure> (package:doctor_app/UI/MeetingScreen.dart:163:19)
E/flutter (29582): <asynchronous suspension>
E/flutter (29582):

**Comment by qt-odabade** [comment]
I'm also getting the same issue
Found any fix for this ?

**Comment by nihalBuildd** [comment]
same here, have anybody got the answer?

**Comment by nihalBuildd** [comment]
I got the solution, its because the api is not getting the user level scope.

go to zoom marketplace , and then go to scope section and give user level access.
